// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestPromart.Models;

namespace TestPromart.Migrations
{
    [DbContext(typeof(OrdenServicioContext))]
    partial class OrdenServicioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestPromart.Models.OrdenServicio", b =>
                {
                    b.Property<int>("NIdSo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaEstimada");

                    b.Property<int>("FechaRegistro");

                    b.Property<int>("IdProveedor");

                    b.Property<int?>("NIdProvNId");

                    b.Property<string>("Observacion");

                    b.Property<string>("Turno");

                    b.HasKey("NIdSo");

                    b.HasIndex("NIdProvNId");

                    b.ToTable("OrdenServicios");
                });

            modelBuilder.Entity("TestPromart.Models.OrdenServicioDet", b =>
                {
                    b.Property<int>("NIdSo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdProducto");

                    b.Property<int>("IdServicio");

                    b.Property<int>("IdServicioDetalle");

                    b.Property<int?>("OrdServicioNIdSo");

                    b.Property<int?>("ProductosNIdP");

                    b.Property<int?>("ServiciosNIdS");

                    b.HasKey("NIdSo");

                    b.HasIndex("OrdServicioNIdSo");

                    b.HasIndex("ProductosNIdP");

                    b.HasIndex("ServiciosNIdS");

                    b.ToTable("OrdenServicioDet");
                });

            modelBuilder.Entity("TestPromart.Models.Producto", b =>
                {
                    b.Property<int>("NIdP")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<string>("Sku");

                    b.HasKey("NIdP");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("TestPromart.Models.Proveedor", b =>
                {
                    b.Property<int>("NId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("NId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("TestPromart.Models.Servicio", b =>
                {
                    b.Property<int>("NIdS")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<string>("SkuManual");

                    b.HasKey("NIdS");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("TestPromart.Models.OrdenServicio", b =>
                {
                    b.HasOne("TestPromart.Models.Proveedor", "NIdProv")
                        .WithMany()
                        .HasForeignKey("NIdProvNId");
                });

            modelBuilder.Entity("TestPromart.Models.OrdenServicioDet", b =>
                {
                    b.HasOne("TestPromart.Models.OrdenServicio", "OrdServicio")
                        .WithMany("OrdenDetail")
                        .HasForeignKey("OrdServicioNIdSo");

                    b.HasOne("TestPromart.Models.Producto", "Productos")
                        .WithMany()
                        .HasForeignKey("ProductosNIdP");

                    b.HasOne("TestPromart.Models.Servicio", "Servicios")
                        .WithMany()
                        .HasForeignKey("ServiciosNIdS");
                });
#pragma warning restore 612, 618
        }
    }
}
